# Generated by Django 3.2.7 on 2022-05-24 21:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ex_Equipe_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='uncategorized', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Former_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='uncategorized', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Former',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lattes', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipe.former_category')),
            ],
        ),
        migrations.CreateModel(
            name='Ex_Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lattes', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='equipe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipe.ex_equipe_categoria')),
            ],
        ),
    ]
