# Generated by Django 3.2.7 on 2022-05-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_ex_equipe_ex_equipe_categoria_former_former_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ex_Equipe',
            new_name='Ex_Membros',
        ),
        migrations.RenameModel(
            old_name='Ex_Equipe_categoria',
            new_name='Ex_Membros_categoria',
        ),
    ]
