# Generated by Django 3.2.7 on 2022-05-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_auto_20220524_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex_membros',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ex_membros',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ex_membros',
            name='lattes',
        ),
        migrations.RemoveField(
            model_name='former',
            name='email',
        ),
        migrations.RemoveField(
            model_name='former',
            name='image',
        ),
        migrations.RemoveField(
            model_name='former',
            name='lattes',
        ),
    ]
