# Generated by Django 3.2.25 on 2024-05-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_auto_20220524_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='equipe.equipe_categoria'),
        ),
    ]
