# Generated by Django 3.2.25 on 2024-05-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
