# Generated by Django 3.2.25 on 2024-05-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0007_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='google_scholar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
