# Generated by Django 3.2.25 on 2024-05-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0008_equipe_google_scholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='categoria',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
