# Generated by Django 3.2.25 on 2024-05-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0009_equipe_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='google_scholar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
